// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVAgWOIZPq00ngO7EcU02FCyogWdbDf28',
    appId: '1:877064445496:web:d953acb9428e8eba52d0cd',
    messagingSenderId: '877064445496',
    projectId: 'peertransfer-app',
    authDomain: 'peertransfer-app.firebaseapp.com',
    storageBucket: 'peertransfer-app.firebasestorage.app',
    measurementId: 'G-9E09WSDGLL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDULp-MYR8bi2dl3Cpf01odez_aLcgKtbs',
    appId: '1:877064445496:android:aeb7d839839d1b2b52d0cd',
    messagingSenderId: '877064445496',
    projectId: 'peertransfer-app',
    storageBucket: 'peertransfer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVsEicDVO_7de3sFOuoGKaPKRN4owpXnk',
    appId: '1:877064445496:ios:06191b8e86c31ea852d0cd',
    messagingSenderId: '877064445496',
    projectId: 'peertransfer-app',
    storageBucket: 'peertransfer-app.firebasestorage.app',
    iosBundleId: 'com.example.p2pFileShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVsEicDVO_7de3sFOuoGKaPKRN4owpXnk',
    appId: '1:877064445496:ios:06191b8e86c31ea852d0cd',
    messagingSenderId: '877064445496',
    projectId: 'peertransfer-app',
    storageBucket: 'peertransfer-app.firebasestorage.app',
    iosBundleId: 'com.example.p2pFileShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVAgWOIZPq00ngO7EcU02FCyogWdbDf28',
    appId: '1:877064445496:web:0efbc6cd16ccf5d452d0cd',
    messagingSenderId: '877064445496',
    projectId: 'peertransfer-app',
    authDomain: 'peertransfer-app.firebaseapp.com',
    storageBucket: 'peertransfer-app.firebasestorage.app',
    measurementId: 'G-JVXVF15BPE',
  );
}
